#------------------------------------------------------------------------------

SOURCEDOUBLELINKEDLIST=DoubleLinkedListTest.cpp
PROGRAMDOUBLELINKEDLIST=doublelinkedlist

SOURCELINKEDLIST=LinkedListTest.cpp
PROGRAMLINKEDLIST=linkedlist

SOURCEQUEUE=QueueTest.cpp
PROGRAMQUEUE=queue

SOURCESTACK=StackTest.cpp
PROGRAMSTACK=stack

MYINCLUDES=/home/scale/g++Projects/gLib/

CFLAGS= -g -Wall -Wextra
MYLIBRARIES=fltk
CC=g++

#------------------------------------------------------------------------------



all: $(PROGRAMDOUBLELINKEDLIST) $(PROGRAMLINKEDLIST) $(PROGRAMQUEUE) $(PROGRAMSTACK)

$(PROGRAMDOUBLELINKEDLIST): $(SOURCEDOUBLELINKEDLIST)

	$(CC) $(SOURCEDOUBLELINKEDLIST) $(CFLAGS) -o$(PROGRAMDOUBLELINKEDLIST)


$(PROGRAMLINKEDLIST): $(SOURCELINKEDLIST)

	$(CC) $(SOURCELINKEDLIST) $(CFLAGS) -o$(PROGRAMLINKEDLIST)


$(PROGRAMQUEUE): $(SOURCEQUEUE)

	$(CC) $(SOURCEQUEUE) $(CFLAGS) -o$(PROGRAMQUEUE)


$(PROGRAMSTACK): $(SOURCESTACK)

	$(CC) $(SOURCESTACK) $(CFLAGS) -o$(PROGRAMSTACK)

clean:

	rm -f $(PROGRAMDOUBLELINKEDLIST)

	rm -f $(PROGRAMLINKEDLIST)

	rm -f $(PROGRAMQUEUE)

	rm -f $(PROGRAMSTACK)




